#!/usr/bin/env bash
# build-release.sh — Build a release DMG and write a local Homebrew cask.
#
# Output in dist/:
#
#   pelagos-ui-<version>-aarch64.dmg     — Tauri .app bundle in a DMG
#   Casks/pelagos-ui.rb                  — Local Homebrew cask (file:// URL)
#
# To install locally:
#   bash scripts/build-release.sh
#   brew install --cask dist/Casks/pelagos-ui.rb
#
# To upgrade an existing install:
#   bash scripts/build-release.sh
#   brew reinstall --cask dist/Casks/pelagos-ui.rb

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="$REPO/dist"

# ---------------------------------------------------------------------------
# Version — read from tauri.conf.json (source of truth)
# ---------------------------------------------------------------------------
VERSION="$(python3 -c "import json,sys; print(json.load(open('$REPO/src-tauri/tauri.conf.json'))['version'])")"
DMG_NAME="pelagos-ui-${VERSION}-aarch64.dmg"

echo "[release] pelagos-ui ${VERSION}"

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
echo "[release] building frontend + Tauri app..."
cd "$REPO"
npm run tauri build 2>&1 | grep -E "Bundling|Finished|Built|Error|error"

TAURI_DMG="$REPO/target/release/bundle/dmg/pelagos-ui_${VERSION}_aarch64.dmg"
if [[ ! -f "$TAURI_DMG" ]]; then
    echo "ERROR: expected DMG not found: $TAURI_DMG"
    exit 1
fi

# ---------------------------------------------------------------------------
# Stage
# ---------------------------------------------------------------------------
mkdir -p "$DIST/Casks"

cp "$TAURI_DMG" "$DIST/$DMG_NAME"
SHA256="$(shasum -a 256 "$DIST/$DMG_NAME" | awk '{print $1}')"
SIZE="$(du -sh "$DIST/$DMG_NAME" | awk '{print $1}')"
echo "[release]   ${SIZE}  sha256: ${SHA256}"

# ---------------------------------------------------------------------------
# Write cask
# ---------------------------------------------------------------------------
cat > "$DIST/Casks/pelagos-ui.rb" <<CASK
# pelagos-ui Homebrew cask
#
# LOCAL VERSION — generated by scripts/build-release.sh.
# Uses file:// URLs pointing at dist/.  The production cask in
# pelagos-containers/homebrew-tap uses https://github.com/... URLs.
#
# To install locally:
#   brew install --cask ${DIST}/Casks/pelagos-ui.rb
#
# To upgrade:
#   bash scripts/build-release.sh
#   brew reinstall --cask ${DIST}/Casks/pelagos-ui.rb

cask "pelagos-ui" do
  version "${VERSION}"
  sha256 "${SHA256}"

  url "file://${DIST}/${DMG_NAME}"
  name "pelagos-ui"
  desc "Desktop GUI for the pelagos container runtime"
  homepage "https://github.com/pelagos-containers/pelagos-ui"

  # Requires pelagos-mac formula: brew install pelagos-containers/tap/pelagos-mac
  app "pelagos-ui.app"

  zap trash: [
    "~/Library/Logs/io.pelagos.ui",
    "~/Library/WebKit/io.pelagos.ui",
    "~/Library/Application Support/io.pelagos.ui",
  ]
end
CASK

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "[release] done."
echo ""
echo "  $DIST/$DMG_NAME"
echo "  $DIST/Casks/pelagos-ui.rb"
echo ""
echo "  To install:"
echo "    brew install --cask $DIST/Casks/pelagos-ui.rb"
echo ""
echo "  To upgrade an existing install:"
echo "    brew reinstall --cask $DIST/Casks/pelagos-ui.rb"
